name: Artur
title: Artur's blog
author: Artur Tamborski
description: Programming and tinkering with electronics.

baseurl:
url: https://arturtamborski.pl

lang: pl_PL
language: pl
encoding: utf-8
timezone: Europe/Warsaw

future: no
unpublished: no
permalink: /:year/:month/:title

disqus:
  id: arturtamborski-pl

twitter:
  username: arturtamborski

author:
  twitter: arturtamborski

social:
  name: Artur Tamborski
  links:
    - https://github.com/arturtamborski
    - https://twitter.com/arturtamborski
    - https://www.linkedin.com/in/arturtamborski
    - https://facebook.com/tamborskiartur

nav:
  local:
    - name: about
      href: /about
    - name: tags
      href: /tags
    - name: feed
      href: /feed.xml

  external:
    - name: github
      href: https://github.com/arturtamborski
    - name: twitter
      href: https://twitter.com/arturtamborski

posts_dir: _posts
pages_dir: pages
drafts_dir: drafts
assets_dir: files
layouts_dir: _layouts
includes_dir: includes

include:
  - pages
  - files

exclude:
  - CNAME
  - drafts
  - license
  - readme.md
  - makefile
  - gemfile
  - Gemfile.lock

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-feed
  - jekyll-redirect-from

scss:
  style: compressed

# compress.html by Jonathan Volebregt
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
