name: Artur
title: Artur's blog
author: Artur Tamborski
description: Programming and tinkering with electronics.

encoding: utf-8
future: false
unpublished: false

baseurl:
url: https://arturtamborski.pl

disqus:
  id: arturtamborski-pl

github:
  username: arturtamborski

twitter:
  username: arturtamborski

author:
  twitter: arturtamborski

social:
  name: Artur Tamborski
  links:
    - https://keybase.io/arturtamborski
    - https://github.com/arturtamborski
    - https://twitter.com/arturtamborski
    - https://www.linkedin.com/in/arturtamborski
    - https://facebook.com/tamborskiartur
    - https://plus.google.com/100097744760992392463

nav:
  local:
    - name: about
      href: /about
    - name: tags
      href: /tags
    - name: feed
      href: /feed.xml

  external:
    - name: github
      href: https://github.com/arturtamborski
    - name: twitter
      href: https://twitter.com/arturtamborski

lang: pl_PL
language: pl
timezone: Europe/Warsaw
permalink: /:year/:month/:title

markdown: kramdown

scss:
  style: compressed

posts_dir: _posts
pages_dir: _pages
drafts_dir: _drafts
assets_dir: files
layouts_dir: _layouts
includes_dir: _includes

include:
  - _pages
  - assets

exclude:
  - _posts/example.md
  - _drafts
  - README.md
  - LICENSE
  - CNAME
  - Gemfile.lock
  - Gemfile

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-feed


# compress.html by Jonathan Volebregt
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
